use_frameworks!
platform :ios, '12.0'

target 'RxTodo' do

	# core RxSwift
  	pod 'RxSwift', '~> 4.0'
  	pod 'RxCocoa', '~> 4.0'
  	pod 'RxDataSources', '~> 3.0'

  	# Community projects
  	pod 'Action', '~> 3.4'
	pod 'NSObject+Rx'
  
  	# Realm database
  	pod 'RealmSwift', '~> 3.0'
  	pod 'RxRealm', '~> 0.7'


end
